services:
  pytorch:
    build: ./pytorch
    volumes:
      - ./data:/work
    ports: 
      - "8888:8888"
    # Nvidia設定追記
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]